### ISSUE TITLE
Get Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by manyang-megantoro** [foo123/AjaxListener.js#1]
I have try this using 

```
function mylistener(req, res)
{
    // API is either 'xhr' or 'fetch'
    console.log('REQUEST', 'API', req.getAPI(), 'Method', req.getMethod(), 'URL', req.getURL(), 'Headers', req.getHeaders(), 'Body', req.getBody());
    console.log('RESPONSE', 'API', res.getAPI(), 'Status', res.getStatus(), 'URL', res.getURL(), 'Headers', res.getHeaders(), 'Body', res.getBody());
}

AjaxListener.install().onRequest(mylistener);
```

In first trial, I success and nothing problem with that, but in another day I have a problem, this function never work and I get error "Failed to execute 'fetch' on 'Window': Illegal invocation"

I use Chrome Version 110.0.5481.77

**Comment by foo123** [comment]
Check this issue if there is something else going wrong 
https://stackoverflow.com/questions/49109878/typeerror-failed-to-execute-fetch-on-window-invalid-value

**Comment by foo123** [comment]
Also share the code you use with fetch so I can test it.

**Comment by foo123** [comment]
Issue fixed in version 1.0.1. Thank you! Closing this.

**Comment by foo123** [comment]
Get newer version 1.0.2 for better fetch handling.

**Comment by foo123** [comment]
New version 1.1.0

**Comment by foo123** [comment]
New version 1.2.0
